# version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "1337:1337"
    volumes:
      - strapi-data:/data
    networks:
      - app-network

volumes:
  strapi-data:

networks:
  app-network:
    driver: bridge